name: Running for ${{ parameters.extensionName }}
appendCommitMessageToRunName: false
trigger: none
parameters:
- name: extensionName
  displayName: 'Select Extension to Sign'
  type: string
  default: ''
  values:
  - TaskExtensions
- name: PublishExtension
  displayName: 'Publish Extension'
  type: boolean
  default: false
- name: ExtensionVersion
  displayName: 'Extension Version (Override) for Public Extension (PROD)'
  type: string
  default: ' '

variables:
- name: CodeQL.Enabled
  value: true
- group: EPS.ESRPSigningProdAME # https://dev.azure.com/mseng/AzureDevOps/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=473&path=EsrpSigningProd

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: TaskExtensions
    type: github
    name: microsoft/azure-devops-extension-tasks
    endpoint: ADOExtensionAPIGHToken2
    ref: refs/heads/main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: 1ESPtTfsAgentBuildPoolSDL
      sourceRepositoriesToScan:
        include:
        - repository: ${{ parameters.extensionName }}
      spotBugs:
        enabled: false
      binskim:
        break: false
    pool:
      name: 1ESPtTfsAgentBuildPool1
    customBuildTags:
    - ES365AIMigrationTooling
    - Extension-${{ parameters.extensionName }}
    - ${{ if eq(parameters.PublishExtension, true) }}:
      - PublishExtensionTrue
    - ${{ if eq(parameters.PublishExtension, false) }}:
      - PublishExtensionFalse
    - ${{ if not(or(eq(trim(parameters.ExtensionVersion), ''), eq(trim(parameters.ExtensionVersion), ' '))) }}:
      - ExtensionVersion-${{ parameters.ExtensionVersion }}
    - ${{ if or(eq(trim(parameters.ExtensionVersion), ''), eq(trim(parameters.ExtensionVersion), ' ')) }}:
      - AutoVersion-Patch

    stages:
    - ${{ if eq(parameters.extensionName, 'TaskExtensions') }}:
      - template: Sign-Tasks.yml
        parameters:
          PublishExtension: ${{ parameters.PublishExtension }}
          ExtensionVersion: ${{ trim(parameters.ExtensionVersion) }}
          RepositoryName: "microsoft/azure-devops-extension-tasks"
          UpdateTaskVersion: true
