name: Check SemVer

on:
  push:
    branches: ['main']
    tags:
      - '*'
  workflow_dispatch:

permissions: {}

jobs:
  check-semver:
    permissions:
      contents: write

    concurrency:
      group: '${{ github.workflow }}'
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: jessehouwing/actions-semver-checker@137abf7f17b0685d85c5511bc94acc944e717408 # v2.0.6
        with:
          floating-versions-use: tags
          check-minor-version: error
          check-release-immutability: none
          ignore-preview-releases: true
          check-releases: error
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-fix: false
